basePath: /
host: localhost:3002
info:
  contact: {}
  description: This is a simple echo server
  license:
    name: Apache 2.0
  title: Simple Echo Service
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - '*/*'
      description: Create a new product
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a new product
      tags:
      - root
swagger: "2.0"
